package dataobject

type PollsDO struct {
	Id             int64  `db:"id"`
	PollId         int64  `db:"poll_id"`
	Creator        int32  `db:"creator"`
	Question       string `db:"question"`
	Closed         int8   `db:"closed"`
	PublicVoters   int8   `db:"public_voters"`
	MultipleChoice int8   `db:"multiple_choice"`
	Quiz           int8   `db:"quiz"`
	CorrectAnswer0 int8   `db:"correct_answer0"`
	CorrectAnswer1 int8   `db:"correct_answer1"`
	CorrectAnswer2 int8   `db:"correct_answer2"`
	CorrectAnswer3 int8   `db:"correct_answer3"`
	CorrectAnswer4 int8   `db:"correct_answer4"`
	CorrectAnswer5 int8   `db:"correct_answer5"`
	CorrectAnswer6 int8   `db:"correct_answer6"`
	CorrectAnswer7 int8   `db:"correct_answer7"`
	CorrectAnswer8 int8   `db:"correct_answer8"`
	CorrectAnswer9 int8   `db:"correct_answer9"`
	Text0          string `db:"text0"`
	Option0        string `db:"option0"`
	Voters0        int32  `db:"voters0"`
	Text1          string `db:"text1"`
	Option1        string `db:"option1"`
	Voters1        int32  `db:"voters1"`
	Text2          string `db:"text2"`
	Option2        string `db:"option2"`
	Voters2        int32  `db:"voters2"`
	Text3          string `db:"text3"`
	Option3        string `db:"option3"`
	Voters3        int32  `db:"voters3"`
	Text4          string `db:"text4"`
	Option4        string `db:"option4"`
	Voters4        int32  `db:"voters4"`
	Text5          string `db:"text5"`
	Option5        string `db:"option5"`
	Voters5        int32  `db:"voters5"`
	Text6          string `db:"text6"`
	Option6        string `db:"option6"`
	Voters6        int32  `db:"voters6"`
	Text7          string `db:"text7"`
	Option7        string `db:"option7"`
	Voters7        int32  `db:"voters7"`
	Text8          string `db:"text8"`
	Option8        string `db:"option8"`
	Voters8        int32  `db:"voters8"`
	Text9          string `db:"text9"`
	Option9        string `db:"option9"`
	Voters9        int32  `db:"voters9"`
	Date2          int32  `db:"date2"`
}
