// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: schema.tl.transport_service.proto

package mtproto // import "open.chat/mtproto"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// --------------------------------------------------------------------------------------------
// rpc_drop_answer#58e4a740 req_msg_id:long = RpcDropAnswer;
type TLRpcDropAnswer struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	ReqMsgId             int64         `protobuf:"varint,2,opt,name=req_msg_id,json=reqMsgId,proto3" json:"req_msg_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLRpcDropAnswer) Reset()         { *m = TLRpcDropAnswer{} }
func (m *TLRpcDropAnswer) String() string { return proto.CompactTextString(m) }
func (*TLRpcDropAnswer) ProtoMessage()    {}
func (*TLRpcDropAnswer) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_transport_service_0266b0e2ada5186f, []int{0}
}
func (m *TLRpcDropAnswer) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TLRpcDropAnswer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TLRpcDropAnswer.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *TLRpcDropAnswer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLRpcDropAnswer.Merge(dst, src)
}
func (m *TLRpcDropAnswer) XXX_Size() int {
	return m.Size()
}
func (m *TLRpcDropAnswer) XXX_DiscardUnknown() {
	xxx_messageInfo_TLRpcDropAnswer.DiscardUnknown(m)
}

var xxx_messageInfo_TLRpcDropAnswer proto.InternalMessageInfo

func (m *TLRpcDropAnswer) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLRpcDropAnswer) GetReqMsgId() int64 {
	if m != nil {
		return m.ReqMsgId
	}
	return 0
}

// --------------------------------------------------------------------------------------------
// get_future_salts#b921bd04 num:int = FutureSalts;
type TLGetFutureSalts struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	Num                  int32         `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLGetFutureSalts) Reset()         { *m = TLGetFutureSalts{} }
func (m *TLGetFutureSalts) String() string { return proto.CompactTextString(m) }
func (*TLGetFutureSalts) ProtoMessage()    {}
func (*TLGetFutureSalts) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_transport_service_0266b0e2ada5186f, []int{1}
}
func (m *TLGetFutureSalts) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TLGetFutureSalts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TLGetFutureSalts.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *TLGetFutureSalts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLGetFutureSalts.Merge(dst, src)
}
func (m *TLGetFutureSalts) XXX_Size() int {
	return m.Size()
}
func (m *TLGetFutureSalts) XXX_DiscardUnknown() {
	xxx_messageInfo_TLGetFutureSalts.DiscardUnknown(m)
}

var xxx_messageInfo_TLGetFutureSalts proto.InternalMessageInfo

func (m *TLGetFutureSalts) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLGetFutureSalts) GetNum() int32 {
	if m != nil {
		return m.Num
	}
	return 0
}

// --------------------------------------------------------------------------------------------
// ping#7abe77ec ping_id:long = Pong;
type TLPing struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	PingId               int64         `protobuf:"varint,2,opt,name=ping_id,json=pingId,proto3" json:"ping_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLPing) Reset()         { *m = TLPing{} }
func (m *TLPing) String() string { return proto.CompactTextString(m) }
func (*TLPing) ProtoMessage()    {}
func (*TLPing) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_transport_service_0266b0e2ada5186f, []int{2}
}
func (m *TLPing) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TLPing) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TLPing.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *TLPing) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLPing.Merge(dst, src)
}
func (m *TLPing) XXX_Size() int {
	return m.Size()
}
func (m *TLPing) XXX_DiscardUnknown() {
	xxx_messageInfo_TLPing.DiscardUnknown(m)
}

var xxx_messageInfo_TLPing proto.InternalMessageInfo

func (m *TLPing) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLPing) GetPingId() int64 {
	if m != nil {
		return m.PingId
	}
	return 0
}

// --------------------------------------------------------------------------------------------
// ping_delay_disconnect#f3427b8c ping_id:long disconnect_delay:int = Pong;
type TLPingDelayDisconnect struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	PingId               int64         `protobuf:"varint,2,opt,name=ping_id,json=pingId,proto3" json:"ping_id,omitempty"`
	DisconnectDelay      int32         `protobuf:"varint,3,opt,name=disconnect_delay,json=disconnectDelay,proto3" json:"disconnect_delay,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLPingDelayDisconnect) Reset()         { *m = TLPingDelayDisconnect{} }
func (m *TLPingDelayDisconnect) String() string { return proto.CompactTextString(m) }
func (*TLPingDelayDisconnect) ProtoMessage()    {}
func (*TLPingDelayDisconnect) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_transport_service_0266b0e2ada5186f, []int{3}
}
func (m *TLPingDelayDisconnect) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TLPingDelayDisconnect) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TLPingDelayDisconnect.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *TLPingDelayDisconnect) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLPingDelayDisconnect.Merge(dst, src)
}
func (m *TLPingDelayDisconnect) XXX_Size() int {
	return m.Size()
}
func (m *TLPingDelayDisconnect) XXX_DiscardUnknown() {
	xxx_messageInfo_TLPingDelayDisconnect.DiscardUnknown(m)
}

var xxx_messageInfo_TLPingDelayDisconnect proto.InternalMessageInfo

func (m *TLPingDelayDisconnect) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLPingDelayDisconnect) GetPingId() int64 {
	if m != nil {
		return m.PingId
	}
	return 0
}

func (m *TLPingDelayDisconnect) GetDisconnectDelay() int32 {
	if m != nil {
		return m.DisconnectDelay
	}
	return 0
}

// --------------------------------------------------------------------------------------------
// destroy_session#e7512126 session_id:long = DestroySessionRes;
type TLDestroySession struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	SessionId            int64         `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLDestroySession) Reset()         { *m = TLDestroySession{} }
func (m *TLDestroySession) String() string { return proto.CompactTextString(m) }
func (*TLDestroySession) ProtoMessage()    {}
func (*TLDestroySession) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_transport_service_0266b0e2ada5186f, []int{4}
}
func (m *TLDestroySession) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TLDestroySession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TLDestroySession.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *TLDestroySession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLDestroySession.Merge(dst, src)
}
func (m *TLDestroySession) XXX_Size() int {
	return m.Size()
}
func (m *TLDestroySession) XXX_DiscardUnknown() {
	xxx_messageInfo_TLDestroySession.DiscardUnknown(m)
}

var xxx_messageInfo_TLDestroySession proto.InternalMessageInfo

func (m *TLDestroySession) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLDestroySession) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

// --------------------------------------------------------------------------------------------
// contest.saveDeveloperInfo#9a5f6e95 vk_id:int name:string phone_number:string age:int city:string = Bool;
type TLContestSaveDeveloperInfo struct {
	Constructor          TLConstructor `protobuf:"varint,1,opt,name=constructor,proto3,enum=mtproto.TLConstructor" json:"constructor,omitempty"`
	VkId                 int32         `protobuf:"varint,2,opt,name=vk_id,json=vkId,proto3" json:"vk_id,omitempty"`
	Name                 string        `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	PhoneNumber          string        `protobuf:"bytes,4,opt,name=phone_number,json=phoneNumber,proto3" json:"phone_number,omitempty"`
	Age                  int32         `protobuf:"varint,5,opt,name=age,proto3" json:"age,omitempty"`
	City                 string        `protobuf:"bytes,6,opt,name=city,proto3" json:"city,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *TLContestSaveDeveloperInfo) Reset()         { *m = TLContestSaveDeveloperInfo{} }
func (m *TLContestSaveDeveloperInfo) String() string { return proto.CompactTextString(m) }
func (*TLContestSaveDeveloperInfo) ProtoMessage()    {}
func (*TLContestSaveDeveloperInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_schema_tl_transport_service_0266b0e2ada5186f, []int{5}
}
func (m *TLContestSaveDeveloperInfo) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *TLContestSaveDeveloperInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_TLContestSaveDeveloperInfo.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalTo(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (dst *TLContestSaveDeveloperInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TLContestSaveDeveloperInfo.Merge(dst, src)
}
func (m *TLContestSaveDeveloperInfo) XXX_Size() int {
	return m.Size()
}
func (m *TLContestSaveDeveloperInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_TLContestSaveDeveloperInfo.DiscardUnknown(m)
}

var xxx_messageInfo_TLContestSaveDeveloperInfo proto.InternalMessageInfo

func (m *TLContestSaveDeveloperInfo) GetConstructor() TLConstructor {
	if m != nil {
		return m.Constructor
	}
	return CRC32_UNKNOWN
}

func (m *TLContestSaveDeveloperInfo) GetVkId() int32 {
	if m != nil {
		return m.VkId
	}
	return 0
}

func (m *TLContestSaveDeveloperInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TLContestSaveDeveloperInfo) GetPhoneNumber() string {
	if m != nil {
		return m.PhoneNumber
	}
	return ""
}

func (m *TLContestSaveDeveloperInfo) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *TLContestSaveDeveloperInfo) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func init() {
	proto.RegisterType((*TLRpcDropAnswer)(nil), "mtproto.TL_rpc_drop_answer")
	proto.RegisterType((*TLGetFutureSalts)(nil), "mtproto.TL_get_future_salts")
	proto.RegisterType((*TLPing)(nil), "mtproto.TL_ping")
	proto.RegisterType((*TLPingDelayDisconnect)(nil), "mtproto.TL_ping_delay_disconnect")
	proto.RegisterType((*TLDestroySession)(nil), "mtproto.TL_destroy_session")
	proto.RegisterType((*TLContestSaveDeveloperInfo)(nil), "mtproto.TL_contest_saveDeveloperInfo")
}
func (this *TLRpcDropAnswer) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&mtproto.TLRpcDropAnswer{")
	s = append(s, "Constructor: "+fmt.Sprintf("%#v", this.Constructor)+",\n")
	s = append(s, "ReqMsgId: "+fmt.Sprintf("%#v", this.ReqMsgId)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TLGetFutureSalts) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&mtproto.TLGetFutureSalts{")
	s = append(s, "Constructor: "+fmt.Sprintf("%#v", this.Constructor)+",\n")
	s = append(s, "Num: "+fmt.Sprintf("%#v", this.Num)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TLPing) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&mtproto.TLPing{")
	s = append(s, "Constructor: "+fmt.Sprintf("%#v", this.Constructor)+",\n")
	s = append(s, "PingId: "+fmt.Sprintf("%#v", this.PingId)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TLPingDelayDisconnect) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 7)
	s = append(s, "&mtproto.TLPingDelayDisconnect{")
	s = append(s, "Constructor: "+fmt.Sprintf("%#v", this.Constructor)+",\n")
	s = append(s, "PingId: "+fmt.Sprintf("%#v", this.PingId)+",\n")
	s = append(s, "DisconnectDelay: "+fmt.Sprintf("%#v", this.DisconnectDelay)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TLDestroySession) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 6)
	s = append(s, "&mtproto.TLDestroySession{")
	s = append(s, "Constructor: "+fmt.Sprintf("%#v", this.Constructor)+",\n")
	s = append(s, "SessionId: "+fmt.Sprintf("%#v", this.SessionId)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *TLContestSaveDeveloperInfo) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 10)
	s = append(s, "&mtproto.TLContestSaveDeveloperInfo{")
	s = append(s, "Constructor: "+fmt.Sprintf("%#v", this.Constructor)+",\n")
	s = append(s, "VkId: "+fmt.Sprintf("%#v", this.VkId)+",\n")
	s = append(s, "Name: "+fmt.Sprintf("%#v", this.Name)+",\n")
	s = append(s, "PhoneNumber: "+fmt.Sprintf("%#v", this.PhoneNumber)+",\n")
	s = append(s, "Age: "+fmt.Sprintf("%#v", this.Age)+",\n")
	s = append(s, "City: "+fmt.Sprintf("%#v", this.City)+",\n")
	if this.XXX_unrecognized != nil {
		s = append(s, "XXX_unrecognized:"+fmt.Sprintf("%#v", this.XXX_unrecognized)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func valueToGoStringSchemaTlTransportService(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func (m *TLRpcDropAnswer) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TLRpcDropAnswer) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Constructor != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.Constructor))
	}
	if m.ReqMsgId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.ReqMsgId))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TLGetFutureSalts) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TLGetFutureSalts) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Constructor != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.Constructor))
	}
	if m.Num != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.Num))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TLPing) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TLPing) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Constructor != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.Constructor))
	}
	if m.PingId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.PingId))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TLPingDelayDisconnect) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TLPingDelayDisconnect) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Constructor != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.Constructor))
	}
	if m.PingId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.PingId))
	}
	if m.DisconnectDelay != 0 {
		dAtA[i] = 0x18
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.DisconnectDelay))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TLDestroySession) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TLDestroySession) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Constructor != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.Constructor))
	}
	if m.SessionId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.SessionId))
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func (m *TLContestSaveDeveloperInfo) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TLContestSaveDeveloperInfo) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Constructor != 0 {
		dAtA[i] = 0x8
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.Constructor))
	}
	if m.VkId != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.VkId))
	}
	if len(m.Name) > 0 {
		dAtA[i] = 0x1a
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(len(m.Name)))
		i += copy(dAtA[i:], m.Name)
	}
	if len(m.PhoneNumber) > 0 {
		dAtA[i] = 0x22
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(len(m.PhoneNumber)))
		i += copy(dAtA[i:], m.PhoneNumber)
	}
	if m.Age != 0 {
		dAtA[i] = 0x28
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(m.Age))
	}
	if len(m.City) > 0 {
		dAtA[i] = 0x32
		i++
		i = encodeVarintSchemaTlTransportService(dAtA, i, uint64(len(m.City)))
		i += copy(dAtA[i:], m.City)
	}
	if m.XXX_unrecognized != nil {
		i += copy(dAtA[i:], m.XXX_unrecognized)
	}
	return i, nil
}

func encodeVarintSchemaTlTransportService(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *TLRpcDropAnswer) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Constructor != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.Constructor))
	}
	if m.ReqMsgId != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.ReqMsgId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TLGetFutureSalts) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Constructor != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.Constructor))
	}
	if m.Num != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.Num))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TLPing) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Constructor != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.Constructor))
	}
	if m.PingId != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.PingId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TLPingDelayDisconnect) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Constructor != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.Constructor))
	}
	if m.PingId != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.PingId))
	}
	if m.DisconnectDelay != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.DisconnectDelay))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TLDestroySession) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Constructor != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.Constructor))
	}
	if m.SessionId != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.SessionId))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *TLContestSaveDeveloperInfo) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Constructor != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.Constructor))
	}
	if m.VkId != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.VkId))
	}
	l = len(m.Name)
	if l > 0 {
		n += 1 + l + sovSchemaTlTransportService(uint64(l))
	}
	l = len(m.PhoneNumber)
	if l > 0 {
		n += 1 + l + sovSchemaTlTransportService(uint64(l))
	}
	if m.Age != 0 {
		n += 1 + sovSchemaTlTransportService(uint64(m.Age))
	}
	l = len(m.City)
	if l > 0 {
		n += 1 + l + sovSchemaTlTransportService(uint64(l))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovSchemaTlTransportService(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozSchemaTlTransportService(x uint64) (n int) {
	return sovSchemaTlTransportService(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *TLRpcDropAnswer) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaTlTransportService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TL_rpc_drop_answer: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TL_rpc_drop_answer: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Constructor", wireType)
			}
			m.Constructor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Constructor |= (TLConstructor(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReqMsgId", wireType)
			}
			m.ReqMsgId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReqMsgId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaTlTransportService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaTlTransportService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TLGetFutureSalts) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaTlTransportService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TL_get_future_salts: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TL_get_future_salts: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Constructor", wireType)
			}
			m.Constructor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Constructor |= (TLConstructor(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Num", wireType)
			}
			m.Num = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Num |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaTlTransportService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaTlTransportService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TLPing) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaTlTransportService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TL_ping: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TL_ping: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Constructor", wireType)
			}
			m.Constructor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Constructor |= (TLConstructor(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PingId", wireType)
			}
			m.PingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PingId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaTlTransportService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaTlTransportService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TLPingDelayDisconnect) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaTlTransportService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TL_ping_delay_disconnect: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TL_ping_delay_disconnect: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Constructor", wireType)
			}
			m.Constructor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Constructor |= (TLConstructor(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PingId", wireType)
			}
			m.PingId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PingId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field DisconnectDelay", wireType)
			}
			m.DisconnectDelay = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.DisconnectDelay |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaTlTransportService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaTlTransportService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TLDestroySession) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaTlTransportService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TL_destroy_session: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TL_destroy_session: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Constructor", wireType)
			}
			m.Constructor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Constructor |= (TLConstructor(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SessionId", wireType)
			}
			m.SessionId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SessionId |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaTlTransportService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaTlTransportService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *TLContestSaveDeveloperInfo) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowSchemaTlTransportService
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: TL_contest_saveDeveloperInfo: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: TL_contest_saveDeveloperInfo: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Constructor", wireType)
			}
			m.Constructor = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Constructor |= (TLConstructor(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field VkId", wireType)
			}
			m.VkId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.VkId |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchemaTlTransportService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PhoneNumber", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchemaTlTransportService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PhoneNumber = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Age", wireType)
			}
			m.Age = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Age |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field City", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthSchemaTlTransportService
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.City = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipSchemaTlTransportService(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthSchemaTlTransportService
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipSchemaTlTransportService(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowSchemaTlTransportService
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowSchemaTlTransportService
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthSchemaTlTransportService
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowSchemaTlTransportService
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipSchemaTlTransportService(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthSchemaTlTransportService = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowSchemaTlTransportService   = fmt.Errorf("proto: integer overflow")
)

func init() {
	proto.RegisterFile("schema.tl.transport_service.proto", fileDescriptor_schema_tl_transport_service_0266b0e2ada5186f)
}

var fileDescriptor_schema_tl_transport_service_0266b0e2ada5186f = []byte{
	// 453 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x93, 0xcf, 0x6e, 0xd4, 0x30,
	0x10, 0xc6, 0x09, 0xdd, 0x3f, 0xd4, 0x45, 0x50, 0xa5, 0x02, 0x42, 0x55, 0xa2, 0x36, 0xa7, 0x72,
	0x20, 0x91, 0xda, 0x0b, 0x67, 0xe8, 0x25, 0x52, 0xe0, 0x10, 0xe5, 0x84, 0x90, 0x2c, 0xaf, 0x3d,
	0xeb, 0x8d, 0x9a, 0xd8, 0xa9, 0x3d, 0x09, 0xda, 0x37, 0xe9, 0x23, 0x21, 0x4e, 0x3c, 0x02, 0x2c,
	0x2f, 0xc0, 0x23, 0xa0, 0x38, 0x41, 0xe1, 0xbe, 0xe2, 0x94, 0x6f, 0x3e, 0x27, 0xdf, 0x6f, 0x46,
	0x19, 0x93, 0x0b, 0xcb, 0x37, 0x50, 0xb3, 0x18, 0xab, 0x18, 0x0d, 0x53, 0xb6, 0xd1, 0x06, 0xa9,
	0x05, 0xd3, 0x95, 0x1c, 0xe2, 0xc6, 0x68, 0xd4, 0xfe, 0xb2, 0x46, 0x27, 0x4e, 0xdf, 0xc8, 0x12,
	0x37, 0xed, 0x2a, 0xe6, 0xba, 0x4e, 0xa4, 0x96, 0x3a, 0x71, 0xf6, 0xaa, 0x5d, 0xbb, 0xca, 0x15,
	0x4e, 0x0d, 0xdf, 0x9d, 0x3e, 0x9b, 0xa2, 0xb9, 0xe1, 0xd7, 0x57, 0x83, 0x1d, 0x55, 0xc4, 0x2f,
	0x32, 0x6a, 0x1a, 0x4e, 0x85, 0xd1, 0x0d, 0x65, 0xca, 0x7e, 0x01, 0xe3, 0xbf, 0x25, 0x47, 0x5c,
	0x2b, 0x8b, 0xa6, 0xe5, 0xa8, 0x4d, 0xe0, 0x9d, 0x7b, 0x97, 0x4f, 0xae, 0x9e, 0xc7, 0x23, 0x3a,
	0x2e, 0xb2, 0xf7, 0xd3, 0x69, 0xfe, 0xef, 0xab, 0xfe, 0x19, 0x21, 0x06, 0xee, 0x68, 0x6d, 0x25,
	0x2d, 0x45, 0xf0, 0xf0, 0xdc, 0xbb, 0x3c, 0xc8, 0x1f, 0x19, 0xb8, 0xfb, 0x60, 0x65, 0x2a, 0x22,
	0x46, 0x4e, 0x8a, 0x8c, 0x4a, 0x40, 0xba, 0x6e, 0xb1, 0x35, 0x40, 0x2d, 0xab, 0xd0, 0xee, 0x81,
	0x3b, 0x26, 0x07, 0xaa, 0xad, 0x1d, 0x67, 0x9e, 0xf7, 0x32, 0xfa, 0x4c, 0x96, 0x45, 0x46, 0x9b,
	0x52, 0xc9, 0x3d, 0x62, 0x5f, 0x90, 0x65, 0x9f, 0x30, 0x8d, 0xb0, 0xe8, 0xcb, 0x54, 0x44, 0xf7,
	0x1e, 0x09, 0xc6, 0x78, 0x2a, 0xa0, 0x62, 0x5b, 0x2a, 0x4a, 0xcb, 0xb5, 0x52, 0xc0, 0xf1, 0x3f,
	0xf0, 0xfc, 0xd7, 0xe4, 0x78, 0x02, 0x0c, 0xc4, 0xe0, 0xc0, 0x0d, 0xfb, 0x74, 0xf2, 0x6f, 0x7a,
	0x3b, 0xaa, 0xdd, 0x9f, 0x14, 0x60, 0xd1, 0xe8, 0x2d, 0xb5, 0x60, 0x6d, 0xa9, 0xd5, 0x1e, 0x3d,
	0xbd, 0x22, 0x64, 0x0c, 0x99, 0xda, 0x3a, 0x1c, 0x9d, 0x54, 0x44, 0xdf, 0x3c, 0x72, 0x56, 0x64,
	0x94, 0x6b, 0x85, 0x60, 0x91, 0x5a, 0xd6, 0xc1, 0x0d, 0x74, 0x50, 0xe9, 0x06, 0x4c, 0xaa, 0xd6,
	0x7a, 0x0f, 0xf2, 0x09, 0x99, 0x77, 0xb7, 0x7f, 0xa1, 0xf3, 0x7c, 0xd6, 0xdd, 0xa6, 0xc2, 0xf7,
	0xc9, 0x4c, 0xb1, 0x1a, 0xdc, 0xf4, 0x87, 0xb9, 0xd3, 0xfe, 0x05, 0x79, 0xdc, 0x6c, 0xb4, 0x02,
	0xaa, 0xda, 0x7a, 0x05, 0x26, 0x98, 0xb9, 0xb3, 0x23, 0xe7, 0x7d, 0x74, 0x56, 0xbf, 0x20, 0x4c,
	0x42, 0x30, 0x1f, 0x16, 0x84, 0x49, 0xe8, 0x83, 0x78, 0x89, 0xdb, 0x60, 0x31, 0x04, 0xf5, 0xfa,
	0x5d, 0xf2, 0xfb, 0x67, 0xe8, 0x7d, 0xdd, 0x85, 0xde, 0xf7, 0x5d, 0xe8, 0xfd, 0xd8, 0x85, 0xde,
	0xfd, 0xaf, 0xf0, 0xc1, 0xa7, 0x97, 0xee, 0xfa, 0xf0, 0x0d, 0xc3, 0x84, 0x57, 0xad, 0x45, 0x30,
	0xc9, 0xd8, 0xfd, 0x6a, 0xe1, 0x1e, 0xd7, 0x7f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x46, 0xa1, 0x45,
	0x8f, 0xb1, 0x03, 0x00, 0x00,
}
